# -*- coding: utf-8 -*-
"""Cuong - Small - Model 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14A7wCSWXYOw3cB9Tho6carycCRqxm05r
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install torch torchvision torchaudio
# %pip install transformers==4.52.4 datasets huggingface_hub accelerate sentencepiece

from datasets import load_dataset, get_dataset_config_names
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM

import torch
import re

import sys

class Tee:
    def __init__(self, *files):
        self.files = files

    def write(self, obj):
        for f in self.files:
            f.write(obj)
            f.flush()

    def flush(self):
        for f in self.files:
            f.flush()


log_file = open(
    "Cuong_small_model3_2nd_attempt_en.txt",
    "a",
    encoding="utf-8"
)

sys.stdout = Tee(sys.stdout, log_file)

# Login
login(token="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")


# Check available configs
configs = get_dataset_config_names("Qwen/PolyMath")

# Load datasets
ds_vi = load_dataset("Qwen/PolyMath", "vi")
ds_en = load_dataset("Qwen/PolyMath", "en")


device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained("sail/Sailor2-1B-Chat")
model = AutoModelForCausalLM.from_pretrained("sail/Sailor2-1B-Chat")
model.to(device)


for level in ds_en.keys():
    match_count = 0
    print(f"\n========== {level.upper()} ==========\n")

    if level != "random":

        dataset = ds_en[level]

        for i in range(len(dataset)):
            if i >= 0:
                question = dataset[i]["question"]
                ground_truth = str(dataset[i]["answer"]).strip()

                print("ID:", dataset[i]["id"])
                print("Question:", question)

                # Prompt
                messages = [
                    {
                        "role": "user",
                        "content":
                        question +
                        "\n\nLưu ý: Vui lòng đặt câu trả lời cuối cùng trong $\\boxed{}$."
                    }
                ]

                # Tokenize
                inputs = tokenizer.apply_chat_template(
                    messages,
                    add_generation_prompt=True,
                    tokenize=True,
                    return_dict=True,
                    return_tensors="pt",
                ).to(model.device)

                # Inference
                with torch.no_grad():

                    outputs = model.generate(
                        **inputs,
                        max_new_tokens=2000,
                        do_sample=False
                    )

                # Decode response
                response = tokenizer.decode(
                    outputs[0][inputs["input_ids"].shape[-1]:],
                    skip_special_tokens=True
                )

                print("Model's Full Answer:", response)

                # =========================================
                # Extract answer inside \boxed{}
                # =========================================

                match = re.search(r'\\boxed\{(.*?)\}', response)

                if match:
                    extracted_answer = match.group(1).strip()
                else:
                    extracted_answer = "NO_BOXED_ANSWER"

                # =========================================
                # Compare answers
                # =========================================

                if extracted_answer == ground_truth:
                    match_count += 1
                    print(extracted_answer + "--" + ground_truth + " (✅)")
                else:
                    print( extracted_answer + "--" + ground_truth + " (❌)")

                print("Matches: " + str(match_count))
                print("-" * 80)

# =========================================
# Final statistics
# =========================================

        total_questions = len(ds_en[level])

        accuracy = match_count / total_questions

        print(f"\nTotal Matches: {match_count}")
        print(f"Total Questions: {total_questions}")
        print(f"Accuracy: {accuracy:.2%}")

log_file.close()
